# Generated by Django 4.2.4 on 2023-09-05 15:30

from django.db import migrations, models
import django.db.models.deletion
def add_initial_statuses(apps, schema_editor):
    Statuses = apps.get_model('contacts', 'Statuses')
    Statuses.objects.create(status='Активный')
    Statuses.objects.create(status='Неактивный')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=50, verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=255, verbose_name='почта')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ('date_added',),
            },
        ),
        migrations.CreateModel(
            name='ContactsList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.contacts', verbose_name='контакт')),
            ],
            options={
                'verbose_name': 'список контакта',
                'verbose_name_plural': 'списки контактов',
                'ordering': ('list',),
            },
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='статус')),
            ],
            options={
                'verbose_name': 'статус',
                'verbose_name_plural': 'статусы',
                'ordering': ('status',),
            },
        ),
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название списка')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contacts', models.ManyToManyField(through='contacts.ContactsList', to='contacts.contacts')),
            ],
            options={
                'verbose_name': 'список',
                'verbose_name_plural': 'списки',
                'ordering': ('date_added',),
            },
        ),
        migrations.AddField(
            model_name='contactslist',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.lists', verbose_name='список'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_list', to='contacts.lists'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contacts.statuses', verbose_name='статус'),
        ),
        migrations.RunPython(add_initial_statuses),
    ]
