# Generated by Django 4.2.4 on 2023-09-05 15:30

from django.db import migrations, models
import django.db.models.deletion


def add_initial_statuses(apps, schema_editor):
    MailingStatuses = apps.get_model('mailing', 'MailingStatuses')
    MailingStatuses.objects.create(status='завершена')
    MailingStatuses.objects.create(status='создана')
    MailingStatuses.objects.create(status='запущена')

    MailingPeriods = apps.get_model('mailing', 'MailingPeriods')
    MailingPeriods.objects.create(
        period_name='Раз в день',
    )
    MailingPeriods.objects.create(
        period_name='Раз в неделю',
    )
    MailingPeriods.objects.create(
        period_name='Раз в месяц',
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailingPeriods',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                    )),
                ('period_name',
                 models.CharField(blank=True, max_length=100, null=True)),
                ('cron_setting',
                 models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'период рассылки',
                'verbose_name_plural': 'период рассылок',
            },
        ),
        migrations.CreateModel(
            name='MailingStatuses',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                    )),
                ('status', models.CharField(
                    max_length=20, verbose_name='статус рассылки'
                    )),
            ],
            options={
                'verbose_name': 'статус рассылки',
                'verbose_name_plural': 'статусы рассылок',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False,
                    verbose_name='ID'
                    )),
                ('title', models.CharField(
                    blank=True, max_length=255, null=True,
                    verbose_name='название рассылки'
                    )),
                ('mailing_time', models.TimeField(
                    blank=True, null=True, verbose_name='время рассылки'
                    )),
                ('message_title',
                 models.CharField(blank=True, max_length=255, null=True)),
                ('message_content', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(
                    auto_now_add=True, verbose_name='дата создания'
                    )),
                ('date_modified', models.DateTimeField(
                    auto_now=True, verbose_name='дата изменения'
                    )),
                ('mailing_periods', models.ForeignKey(
                    blank=True, null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    to='mailing.mailingperiods'
                    )),
                ('status', models.ForeignKey(
                    default=2, on_delete=django.db.models.deletion.DO_NOTHING,
                    to='mailing.mailingstatuses',
                    verbose_name='статус рассылки'
                    )),
            ],
            options={
                'verbose_name': 'рассылка',
                'verbose_name_plural': 'рассылки',
            },
        ),
        migrations.RunPython(add_initial_statuses),
    ]
